// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1OZ9CY3bcpVaMyujKAva3HvmvgXSgnmg',
    appId: '1:908788633325:android:d93e108caa73bb062f86e4',
    messagingSenderId: '908788633325',
    projectId: 'chat-app-53c3a',
    databaseURL: 'https://chat-app-53c3a-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-53c3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4n2T_ky0myMBEHes1FdZJpc13bIzyTUo',
    appId: '1:908788633325:ios:4c2a629ec27bb41d2f86e4',
    messagingSenderId: '908788633325',
    projectId: 'chat-app-53c3a',
    databaseURL: 'https://chat-app-53c3a-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-53c3a.appspot.com',
    iosBundleId: 'nitish.com.chatApp',
  );

}